apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yml
  - https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/install.yaml
  - rbac.yml

patches:
  - path: argocd-cmd-params-cm-patch.yml
    target:
      kind: ConfigMap
      name: argocd-cmd-params-cm
  - path: argocd-repo-server-seccomp-patch.yml
    target:
      kind: Deployment
      name: argocd-repo-server