apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

resources:
- ../../../../../cert-manager/base

patches:
  - path: cainjector-leader-election-patch.yml
    target:
      kind: Deployment
      name: cert-manager-cainjector
  - path: controller-leader-election-patch.yml
    target:
      kind: Deployment
      name: cert-manager